package com.k2dev.hospital.util;

public enum TestStatus {
	REQUEST_SUBMITTED, REQUEST_ACCEPTED, REQUEST_REJECTED, SAMPLE_COLLECTED, 
	SAMPLE_RECEIVED,RESULT_PENDING, REPORT_UPLOADED,TRANSFERED_TO_OTHER_LAB
}
